### ISSUE TITLE
pybind11 2.0.0 compiling error with gcc 5.4

### ISSUE THREAD

**Issue by hokru** [psi4/psi4#577]
after pulling a few commits to the current version I encounter the following error:

```
[ 99%] Building CXX object src/CMakeFiles/core.dir/export_mints.cc.o
/usr/qc/psi4/psi4/src/export_mints.cc: In function ‘void export_mints(pybind11::module&)’:
/usr/qc/psi4/psi4/src/export_mints.cc:1029:79: error: ‘buffer_protocol’ is not a member of ‘py’
     py::class_<detci::CIvect, std::shared_ptr<detci::CIvect> >(m, "CIVector", py::buffer_protocol(), "docstring")
```

guess it has to do with https://github.com/psi4/psi4/pull/557 which is way over my head.

**Comment by jturney** [comment]
My guess is that pybind11 didn't update in your build directory. Were you reusing a build directory from pre ```git pull```? If so, that's the issue, create a new build directory, configure, and make and it should work. I just built psi4 in a clean build directory with gcc 5.4. If not, then we'll look into it more.

**Comment by hokru** [comment]
I always use a fresh build directory. I found 2 cmake related issues.

1) I noticed 'pybind11_external' is build with the gcc 4.8( system default) instead of the locally installed gcc 5.4. So I added 

```
                   -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}                                                                        
                   -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER} 


```

to [CMakeLists.txt](https://github.com/psi4/psi4/blob/master/external/upstream/pybind11/CMakeLists.txt)  like it is done for the libint cmake file.

2) The second issue is that pybind11 auto-detects python3.4 and psi4 detected python2.7 on my workstation. I fixed it by changing the python version in the CMakeCache.txt file for pybind11 by hand, since I don't know how to tell cmake that.

After rebuilding pybind11 the compilation of psi4 finishes normally.

**Comment by hokru** [comment]
Unclear if it is a related, but running `make test` then leads to the following error:

> Traceback (most recent call last):
  File "/usr/qc/psi4.git/objdir/stage/usr/qc/psi4.bin/bin/psi4", line 140, in <module>
    import psi4
  File "/usr/qc/psi4.git/objdir/stage/usr/qc/psi4.bin/lib//psi4/__init__.py", line 59, in <module>
    raise ImportError("{0}".format(err))
ImportError: To be able to register buffer protocol support for the type 'psi4.core.CIVector' the associated class<>(..) invocation must include the pybind11::buffer_protocol() annotation!

Maybe I manually rebuild pybind11 incorrectly in my attempts to get psi4 compiled.

**Comment by jturney** [comment]
Are the python versions you have the system provided ones or separate ones like anaconda?  Also, what distro of Linux is this on?

**Comment by hokru** [comment]
> Are the python versions you have the system provided ones or separate ones like anaconda?

provided by the distro

> Also, what distro of Linux is this on?

opensuse leap 42.1

**Comment by loriab** [comment]
* Yes, this sounds like a pybind11 update issue. Any pybind11 update requires a _full_ recompile. But it sounds like you've got that taken care of with the fresh objdir. Fortunately, now that pybind has hit 2.0, we plan to stick with that version, so these problems will be fewer.
* Very observant on the compilers detected for pybind. But it really doesn't matter because "compilation" and installation of pybind is just copying a dozen files into place.
* On the python detection, there's two places this could be happening, and one, like the above is irrelevant. It's the second one (in the psi4-core target) that really matters. Could you send me your analogs of the CMake output snippets below? Or send me the whole thing, but it'll have to be both the initial CMake configuration and the psi4-core configuration that runs during the course of the compilation. Psi4 and pybind11 use exactly the same Python detection scheme, so I'm surprised and would like to understand what's happening in your setup.
* As far as actually telling psi4 and cmake what Python to use w/o editing CMakeCache's, I'd recc setting one (EXE) or all of https://github.com/psi4/psi4/blob/master/CMakeLists.txt#L39-L41 . But my impression is that you shouldn't have to.

Main CMake configuration
```
-- Setting (unspecified) option CMAKE_INSTALL_MESSAGE: LAZY
-- Setting (unspecified) option psi4_CXX_STANDARD: 11
-- Found PythonInterp: /theoryfs2/ds/cdsgroup/miniconda/envs/texternals35/bin/python3.5 (found version "3.5.2") 
-- Found PythonLibs: /theoryfs2/ds/cdsgroup/miniconda/envs/texternals35/lib/libpython3.5m.so
-- Found Python 3.5: /theoryfs2/ds/cdsgroup/miniconda/envs/texternals35/bin/python3.5
-- Suitable CheMPS2 could not be located, Building CheMPS2 instead.
-- Suitable dkh could not be located, Building dkh instead.
-- Found libefp: /theoryfs2/ds/cdsgroup/miniconda/envs/texternals35/lib/libefp.so (found version 1.3.0)
-- Found gdma: /theoryfs2/ds/cdsgroup/miniconda/envs/texternals35/lib/libgdma.so (found version 2.2.06)
-- Found libint: /theoryfs2/ds/cdsgroup/miniconda/envs/texternals35/lib/libint.so (found version 1.1.6)
-- Suitable pybind11 could not be located, Building pybind11 instead.
-- Found GCC 5.2.0
```
Then you change into your objdir and pybind11 and other dependencies compile. Finally you get to:
```
Scanning dependencies of target psi4-core
...
-- The CXX compiler identification is Intel 16.0.3.20160415
-- Check for working CXX compiler: /theoryfs2/common/software/intel2016/compilers_and_libraries_2016.3.210/linux/bin/intel64/icpc
-- Check for working CXX compiler: /theoryfs2/common/software/intel2016/compilers_and_libraries_2016.3.210/linux/bin/intel64/icpc -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Checking for restrict keyword
--    keyword found : __restrict__
-- Found PythonInterp: /theoryfs2/ds/cdsgroup/miniconda/envs/texternals35/bin/python3.5 (found version "3.5.2") 
-- Found PythonLibs: /theoryfs2/ds/cdsgroup/miniconda/envs/texternals35/lib/libpython3.5m.so
-- Using pybind11: /theoryfs2/ds/cdsgroup/psi4-compile/hrw-dgasfork3/objdir1/stage/usr/local/psi4/include (version 2.0.0 for Py3.5.2 and -std=c++11)
-- Using Python 3.5: /theoryfs2/ds/cdsgroup/miniconda/envs/texternals35/bin/python3.5
...
-- Using CheMPS2: /theoryfs2/ds/cdsgroup/psi4-compile/hrw-dgasfork3/objdir1/stage/usr/local/psi4/lib/libchemps2.so.2 (version 1.8.3)
-- Using dkh: /theoryfs2/ds/cdsgroup/psi4-compile/hrw-dgasfork3/objdir1/stage/usr/local/psi4/lib/libdkh.so (version 1.2)
-- Using libefp: /theoryfs2/ds/cdsgroup/miniconda/envs/texternals35/lib/libefp.so (version 1.3.0)
-- Using Libxc: /theoryfs2/ds/cdsgroup/psi4-compile/hrw-dgasfork3/objdir1/stage/usr/local/psi4/lib/libxc.so (version 3.0.0)
-- Disabled erd
-- Using gdma: /theoryfs2/ds/cdsgroup/miniconda/envs/texternals35/lib/libgdma.so (version 2.2.06)
-- Using libint: /theoryfs2/ds/cdsgroup/miniconda/envs/texternals35/lib/libint.so (version 1.1.6)
```

**Comment by hokru** [comment]
It seems that were it counts the correct python is used

Main CMake
```
-- Setting (unspecified) option CMAKE_INSTALL_LIBDIR: lib
-- Setting (unspecified) option PYMOD_INSTALL_LIBDIR: /
-- Setting (unspecified) option ENABLE_GENERIC: OFF
-- Setting (unspecified) option CMAKE_INSTALL_MESSAGE: LAZY
-- Setting (unspecified) option psi4_CXX_STANDARD: 11
-- Found PythonInterp: /usr/bin/python (found version "2.7.12") 
-- Found PythonLibs: /usr/lib64/libpython2.7.so
-- Found Python 2.7: /usr/bin/python
-- Found libefp: /usr/qc/psi4.bin/lib/libefp.a (found version 1.3.0)
-- Found libint: /usr/qc/psi4.bin/lib/libint.a (found version 1.1.6)
-- Suitable pybind11 could not be located, Building pybind11 instead.
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED


```

psi4-core cmake:
```
- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/qc/gcc54/bin/gcc
-- Check for working C compiler: /usr/qc/gcc54/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/qc/gcc54/bin/g++
-- Check for working CXX compiler: /usr/qc/gcc54/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Checking for restrict keyword
--    keyword found : __restrict__
-- Found PythonInterp: /usr/bin/python (found version "2.7.12")                                                                                                                                                                                                                
-- Found PythonLibs: /usr/lib64/libpython2.7.so                                                                                                                                                                                                                                
-- Using pybind11: /usr/qc/psi4.git/objdir/stage/usr/qc/psi4.bin/include (version 2.0.0 for Py2.7.12 and -std=c++11)                                                                                                                                                           
-- Using Python 2.7: /usr/bin/python                                                                                                                                                                                                                                           
-- Looking for include file pthread.h                                                                                                                                                                                                                                          
-- Looking for include file pthread.h - found                                                                                                                                                                                                                                  
-- Looking for pthread_create                                                                                                                                                                                                                                                  
-- Looking for pthread_create - found                                                                                                                                                                                                                                          
-- Found Threads: TRUE                                                                                                                                                                                                                                                         
-- Found libdl: /usr/lib64/libdl.so                                                                                                                                                                                                                                            
-- Disabled CheMPS2                                                                                                                                                                                                                                                            
-- Disabled dkh                                                                                                                                                                                                                                                                
-- Using libefp: /usr/qc/psi4.bin/lib/libefp.a (version 1.3.0)                                                                                                                                                                                                                 
-- Disabled erd                                                                                                                                                                                                                                                                
-- Disabled gdma                                                                                                                                                                                                                                                               
-- Using libint: /usr/qc/psi4.bin/lib/libint.a (version 1.1.6)                                                                                                                                                                                                                 
-- Configuring done                                                                                                                                                                                                                                                            
-- Generating done                                                                                                                                                                                                                                                             
```     

And just for completeness the pybind11 part:

```
[ 12%] Performing download step (git clone) for 'pybind11_external'
Cloning into 'pybind11_external'...
Note: checking out 'v2.0.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at e33ef9c... v2.0.0 release
Submodule 'tools/clang' (https://github.com/wjakob/clang-cindex-python3) registered for path 'tools/clang'
Cloning into 'tools/clang'...
Submodule path 'tools/clang': checked out '254c7a91e3c6aa254e113197604dafb443f4d429'
[ 25%] No update step for 'pybind11_external'
[ 25%] No patch step for 'pybind11_external'
[ 31%] Performing configure step for 'pybind11_external'
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/qc/gcc54/bin/gcc
-- Check for working C compiler: /usr/qc/gcc54/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/qc/gcc54/bin/g++
-- Check for working CXX compiler: /usr/qc/gcc54/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /usr/bin/python3.4 (found version "3.4.5") 
-- Found PythonLibs: /usr/lib64/libpython3.4m.so
-- pybind11 v2.0.0
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/qc/psi4.git/objdir/external/upstream/pybind11/pybind11_external-prefix/src/pybind11_external-build

```

For reasons unknown to me I cannot reproduce my previous compilation error. Previously I could reproduce it even when cloning a brand new copy of psi4. Now it finishes the compilation normally.
Maybe the old psi4 installation directory interfered somehow? Just guessing at this point.

However, I still cannot execute psi4.

If I use a symlink to the installed binary I get a python error:
```
    import psi4
ImportError: No module named psi4
```
If I use the full path i get `Intel MKL FATAL ERROR: Cannot load libmkl_avx.so or libmkl_def.so.` instead.

But maybe PR https://github.com/psi4/psi4/pull/563 will fix these things for me.

**Comment by loriab** [comment]
You can fix the `MKL FATAL ERROR` by `LD_PRELOAD=/path/to/libmkl_rt.so psi4`. Yes, #563 or a near relative will fix that properly w/o the preload.

When you run the `bin/psi4` "executable", it hunts down its `lib/psi4/__init__.py` to load psi4 as a python module. I wouldn't have expected it to be confused by a symlink, but I suppose it's possible. I'll have to try it out.

Glad the python detection seems to be working consistently now. Your CMake logs look good (the unnerving "detached HEAD" is just because we pin to tags or commits for dependencies). The odd python3.4 detection in the pybind11 CMake config is to be expected, since none of the environment was passed over to pybind11 because it doesn't matter at that stage. On the now-healed compilation, I was just warned today (@bennybp) that CMake _does_ search your install (not stage, install) dir for dependencies, so perhaps your hunch was right.

**Comment by hokru** [comment]
Thanks for the explanations!

With preload and full path psi4 finally runs :-)

I'll close this issue.
