### ISSUE TITLE
CheMPS2 building issue

### ISSUE THREAD

**Issue by jgonthier** [psi4/psi4#660]
Related to issue #414 : when using the GCC 5.2 trick reported [here](http://psicode.org/psi4manual/master/build_planning.html#faq-modgcc) AND building CheMPS2, which requires to specify the -DCMAKE_AR and -DCMAKE_RANLIB variables, the build fails with the message:

`sorry - this program has been built without plugin support`

I traced it back to gcc-ar for both gcc5.2 from conda and gcc4.8 from the local system being built without plugin support. After more staring, it looks like both gcc-ar are wrappers which call the same /usr/bin/ar, which was built without plugin support.

Anyone can think of a workaround for this ? Could we install a local ar in the conda environment and have gcc5.2 call this one, for example ?

(Note: Edited for clarity.)

**Comment by loriab** [comment]
Uggh, never seen or though about that problem before. What would you simlink to if local gcc doesn't have plugin support either? You could try [this gcc instead](https://anaconda.org/msarahan/gcc_linux-64_linux-cos5-64/files), though I haven't particular hopes. Could you link against the prebuilt chemps2 conda package or do you really need to compile it yourself.?

**Comment by jgonthier** [comment]
Okay, so I guess we can link against the pre-built conda one.
I still tested the gcc you suggested, and after giving the proper gcc-ar and gcc-ranlib to the CMake variables, it complains it cannot find liblto_plugin.so
I checked and the new gcc has only liblto_plugin.a and not the .so

**Comment by loriab** [comment]
At end of [this page](http://www.linuxfromscratch.org/lfs/view/development/chapter06/gcc.html) is a nice run-down of what's supposed to come with a gcc. `liblto_plugin.a` (the static) seems to be an oddity. Glad the conda pkg is working. You're getting it off the `test` [subchanel](https://anaconda.org/psi4/chemps2/files), I hope? `conda install chemps2 -c psi4/label/test` . That should be a well-built one, so let me know if it acts up.

Build options is conda's weakness, I think. For instance, I can't use their `git` because I'm addicted to `git add -p`, and they don't build with perl enabled. There's "features" in the works to counteract this, but I can't suggest any other gcc right off.

**Comment by susilehtola** [comment]
If it's an RHEL cluster you might try using the Developer Toolset's compiler
https://developers.redhat.com/products/developertoolset/overview/

**Comment by jgonthier** [comment]
@loriab Just tried to link with conda chemps2 using the one from the test subchannel. CMake does not seem to realize CheMPS2 is there and keeps saying "no suitable chemps2 found" in spite of me passing
`-DENABLE_CheMPS2=ON -DCMAKE_PREFIX_PATH=/global/home/users/jgonthier/software/miniconda -DCheMPS2_DIR=/global/home/users/jgonthier/software/miniconda` to CMake. Am I forgetting an option/env variable ?

@susilehtola Thanks for the suggestion ! I guess we could also always re-built a local version of gcc... Hopefully if the binary works it won't come to that.

**Comment by loriab** [comment]
`CheMPS2_DIR` is the right approach, but it wants the dir with the `CheMPS2Config.cmake`, not the root dir. [here D for details](http://psicode.org/psi4manual/master/chemps2.html#how-to-configure-chemps2-for-building-psi4). Blame CMake, not me, for that one. I think that's the problem. But if that fails, remove the version from [here](https://github.com/psi4/psi4/blob/master/external/upstream/chemps2/CMakeLists.txt#L2) and [here](https://github.com/psi4/psi4/blob/master/psi4/CMakeLists.txt#L59).

**Comment by jgonthier** [comment]
The CMake variables were not the problem, the version number was. Apparently the one in `-c psi4/label/test` is 1.8.2 and not 1.8.3.

But now, the compilation failed while building liboptions.cc with the following message: 
`cd /global/home/users/jgonthier/software/psi4/objdir_chemps2_ar/psi4-core-prefix/src/psi4-core-build/src/psi4/liboptions && /global/software/sl-6.x86_64/modules/langs/intel/2016.1.150/bin/icpc   -DUSING_LAPACK_MKL -I/global/home/users/jgonthier/software/psi4/psi4/include -I/global/home/users/jgonthier/software/psi4/psi4/src -isystem /global/home/users/jgonthier/software/psi4/objdir_chemps2_ar/stage/usr/local/psi4/include -isystem /global/home/users/jgonthier/software/miniconda/include/python2.7 -isystem /global/software/sl-6.x86_64/modules/langs/intel/2016.1.150/mkl/include  -xHost -qopenmp -O3 -DNDEBUG -fPIC   -std=c++11 -o CMakeFiles/options.dir/liboptions.cc.o -c /global/home/users/jgonthier/software/psi4/psi4/src/psi4/liboptions/liboptions.cc
/global/home/users/jgonthier/software/miniconda/envs/gcc52/gcc/include/c++/bits/stl_iterator_base_types.h(154): error: name followed by "::" must be a class or namespace name
        typedef typename _Iterator::iterator_category iterator_category;
                         ^`

As you can see I use Intel compilers 2016 with Intel MKL, in the GCC 5.2 conda environment. Could it be a problem with Intel compilers ?

**Comment by loriab** [comment]
That's strange, I'm showing it as 1.8.3 (https://anaconda.org/psi4/chemps2/files).

But anyways, any chance this is a rebuild of a pre-Christmas version? That has a faint look of a pybind11 incompatibility. We've been stable at pybind11 2.0 since mid-Jan or so. But any pybind11 change just requires a full wipe out of the build. And CMake is insidious, so if there's even an old pybind11 to be found at the _install_ location, it'll hunt it down and compile bad things with it. So do blow away your builddir and point it to an empty `CMAKE_INSTALL_PREFIX` if there's the least likelihood. (This is why we're sticking with 2.0 for as long as we can.)

**Comment by jgonthier** [comment]
@loriab Regarding the chemps2 version: I just tried on my desktop where everything is fine and it installed 1.8.3. On my cluster with gcc < 4.9, it installs chemps2 1.8.2, if I do the install with the gcc 5 env activated it installs chemps2 1.8.3.

So it seems the version installed depends on the availability of gcc >= 4.9

**Comment by jgonthier** [comment]
And regarding the build: I cloned Psi4 yesterday on a machine where I never had Psi4 installed. The configure is also telling me that pybind11 could not be located and that it will be built.

**Comment by loriab** [comment]
Yeah, CheMPS2 and Psi4 have to use gnu on the same side of 5.1 b/c GCC changed their std::string compatibility. The conda CheMPS2 is def. built against the gcc5.2 in that faq. Usually you have to have the gcc5.2 environment active during configuration and build _or_ pass extra args to the compilers, as below. Doesn't hurt to do both. But you're getting past the compiler checks. I've heard of problems with 2016.1 Intel compiler set. 2016.3 is known good. Actually, @amjames, was this the error you were seeing with early 2016 compilers?

```
PFXC=/theoryfs2/ds/cdsgroup/miniconda/envs/text35
 
${PFXC}/bin/cmake -H. -Bobjdir53 \
 -DCMAKE_C_COMPILER=/theoryfs2/common/software/intel2016/compilers_and_libraries_2016.3.210/linux/bin/intel64/icc \
 -DCMAKE_CXX_COMPILER=/theoryfs2/common/software/intel2016/compilers_and_libraries_2016.3.210/linux/bin/intel64/icpc \
 -DCMAKE_Fortran_COMPILER=/theoryfs2/common/software/intel2016/compilers_and_libraries_2016.3.210/linux/bin/intel64/ifort \
 -DCMAKE_C_FLAGS="-gcc-name=${PFXC}/bin/gcc" \
 -DCMAKE_CXX_FLAGS="-gcc-name=${PFXC}/bin/gcc -gxx-name=${PFXC}/bin/g++" \
 -DCMAKE_Fortran_FLAGS="-gcc-name=${PFXC}/bin/gcc -gxx-name=${PFXC}/bin/g++" \
```

**Comment by jgonthier** [comment]
Okay, I see. I tried again, installing the proper chemps2 from the conda environment, and using gcc/g++ instead of Intel.
Believe it or not, it did work. And the first few tests are ok.

Side note: while testing I noticed that HDF5 detection in CMake fails if 1) HDF5 is installed on the system AND 2) I use conda to install chemps2, which installs hdf5 in conda as well. Should I open a new issue about that ? Or is it too specific a case for being worth the time ?

Thanks for all your input, @loriab and @susilehtola

**Comment by loriab** [comment]
Yay, so building Psi4 w/ gcc/g++5.2 against a pre-built conda chemps2 is what's working?

HDF5 is persnickety in that chemps2 will complain if the HDF5 library it finds at runtime isn't the same one it was compiled against down to the patch level. That is, 1.8.16 and 1.8.17 aren't friendly. So unless you're lucky, you really must use the one that comes with the conda package. Does setting `-DCMAKE_PREFIX_PATH` to the conda env help to overcome the system hdf5? or `HDF5_ROOT`?

**Comment by jgonthier** [comment]
Yes, that's right: gcc5.2 conda env, Psi4 w/gcc/g++5.2 with Intel MKL against pre-built conda chemps2. Everything built in the conda env, tests run out of the conda env, seems to work.

Yes, I tried setting `-DCMAKE_PREFIX_PATH`, but I only tried `HDF5_ROOT` pointing to the system library, which from what you say would fail anyway. I don't have the setup to test this any more though, but I could recreate it if there's enough interest.

**Comment by loriab** [comment]
No need to recreate the HDF5 situation, so long as you can get around it. Which Intel 2016, btw, if it's earlier than 2016.3?

**Comment by jgonthier** [comment]
Intel 2016.1.150 for the compilation failure reported above.

**Comment by amjames** [comment]
Sorry to get in on this kind of late, but that message:
>`...stl_iterator_base_types.h(154): error: name followed by "::" must be a class or namespace name typedef typename _Iterator::iterator_category iterator_category; ^`

Does seem vaguely familiar and I have not been able to get psi4 working on our clusters with intel-16.1.  I have not tried recently though so if it would help you out at all @jgonthier I could try a build tonight and let you know what I see.

**Comment by jgonthier** [comment]
@amjames thank you but I managed to build with gcc in the end, I don't absolutely need intel. We should probably add a note somewhere that there is a problem with Intel 16.1 though.

**Comment by amjames** [comment]
Got it, thanks!

If we are going to put a note about this in a build docs, or put some kind of intel version check into CMake it would probably be best to flush out what exactly is the problem. I have made a note flush out the problem here at some point in the future, but the list of things I have to do that are higher priority is way too long for me to put an estimate on when I will get to it. 

If anyone is interested investigating, please go for it. If anyone has been able to produce a passing build using intel-16.1 please post with any/all info about that build environment so my/anyone else can try to reproduce it!

**Comment by jgonthier** [comment]
This issue was originally about CheMPS2 linking. Should we close it and open one for the Intel compiler issue, that would be easier for people to find ?
