### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by nmayhall** [psi4/psi4#536]
After a recent git pull, psi4 failed to compile. It seems that the error was likely introduced in commit 0d0d1f9 "Reworked exception printing in Psi so all Python Exceptions raise to stdout and psi out". If I revert to the commit just before this I'm able to compile. 

If it helps, I'm running Ubuntu, with gnu compilers. 

Here's the error message: 

`/home/nmayhall/qcSoftware/psi4/psi4.inv.git/psi4/src/core.cc: In function ‘bool py_psi_set_local_option_array(const string&, const string&, const pybind11::list&, psi::DataType*)’:
/home/nmayhall/qcSoftware/psi4/psi4.inv.git/psi4/src/core.cc:786:13: error: ‘isinstance’ is not a member of ‘py’
         if (py::isinstance<py::list>(values[n])) {
             ^
/home/nmayhall/qcSoftware/psi4/psi4.inv.git/psi4/src/core.cc:786:36: error: expected primary-expression before ‘>’ token
         if (py::isinstance<py::list>(values[n])) {
                                    ^
/home/nmayhall/qcSoftware/psi4/psi4.inv.git/psi4/src/core.cc: In function ‘bool py_psi_set_global_option_array(const string&, pybind11::list, psi::DataType*)’:
/home/nmayhall/qcSoftware/psi4/psi4.inv.git/psi4/src/core.cc:834:13: error: ‘isinstance’ is not a member of ‘py’
         if (py::isinstance<py::list>(values[n])) {
             ^
/home/nmayhall/qcSoftware/psi4/psi4.inv.git/psi4/src/core.cc:834:36: error: expected primary-expression before ‘>’ token
         if (py::isinstance<py::list>(values[n])) {
                                    ^
src/CMakeFiles/core.dir/build.make:374: recipe for target 'src/CMakeFiles/core.dir/core.cc.o' failed
make[5]: *** [src/CMakeFiles/core.dir/core.cc.o] Error 1
make[5]: *** Waiting for unfinished jobs....
^Csrc/CMakeFiles/core.dir/build.make:86: recipe for target 'src/CMakeFiles/core.dir/export_mints.cc.o' failed
make[5]: *** [src/CMakeFiles/core.dir/export_mints.cc.o] Interrupt
CMakeFiles/Makefile2:208: recipe for target 'src/CMakeFiles/core.dir/all' failed
make[4]: *** [src/CMakeFiles/core.dir/all] Interrupt
Makefile:127: recipe for target 'all' failed
make[3]: *** [all] Interrupt
CMakeFiles/psi4_core.dir/build.make:111: recipe for target 'psi4_core-prefix/src/psi4_core-stamp/psi4_core-build' failed
make[2]: *** [psi4_core-prefix/src/psi4_core-stamp/psi4_core-build] Interrupt
CMakeFiles/Makefile2:355: recipe for target 'CMakeFiles/psi4_core.dir/all' failed
make[1]: *** [CMakeFiles/psi4_core.dir/all] Interrupt
Makefile:138: recipe for target 'all' failed
make: *** [all] Interrupt
`

**Comment by dgasmith** [comment]
This is actually a PyBind11 version error. It doesn't appear that our CMake is detecting the discrepancy. Please blow away your objdir and recompile from scratch. 

-Daniel Smith

**Comment by nmayhall** [comment]
Thanks Daniel! I looked at the changes and couldn't imagine what was
causing this. I'll follow your suggestion.

Best,
Nick
