### PR TITLE
fmt: clang-format libqt

### PR DESCRIPTION
**Pull request by andysim**
## Description
clang-format libqt

## Questions
- [ ]  If merging this PR will hinder your research b/c you have local edits, protest here or in #1144

## Status
- [x] Ready for review
- [x] Ready for merge

### CODE REVIEW

**Comment by loriab** [comment]
Thanks, @andysim.

@CDSherrill wanted to cast an eye over this diff.

**Comment by andysim** [comment]
Sounds good.  My plan is to just crank through the remaining c-f tasks so that we have diffs to peruse.  I won't make any attempts to do any merging; that way we can just close out any PRs that we don't want to go with.

**Comment by andysim** [comment]
Heads-up; this changed slightly after I fixed the merge conflict introduced by merging #1212

**Comment by loriab** [comment]
Could the conflict have messed up the c-f? Getting the below on all travis builds.

```
[ 15%] Building CXX object src/psi4/libqt/CMakeFiles/qt.dir/ras_set.cc.o
cd /home/travis/build/psi4/psi4/build/psi4-core-prefix/src/psi4-core-build/src/psi4/libqt && /usr/bin/g++-6  -DFC_SYMBOL=2 -I/home/travis/build/psi4/psi4/psi4/include -I/home/travis/build/psi4/psi4/psi4/src -isystem /home/travis/miniconda/envs/p4env/include/python3.5m  -march=native -O3 -DNDEBUG -fPIC   -fopenmp -fvisibility=hidden -std=c++11 -std=c++11 -o CMakeFiles/qt.dir/ras_set.cc.o -c /home/travis/build/psi4/psi4/psi4/src/psi4/libqt/ras_set.cc
[ 15%] Building CXX object src/psi4/libqt/CMakeFiles/qt.dir/reorder_qt.cc.o
cd /home/travis/build/psi4/psi4/build/psi4-core-prefix/src/psi4-core-build/src/psi4/libqt && /usr/bin/g++-6  -DFC_SYMBOL=2 -I/home/travis/build/psi4/psi4/psi4/include -I/home/travis/build/psi4/psi4/psi4/src -isystem /home/travis/miniconda/envs/p4env/include/python3.5m  -march=native -O3 -DNDEBUG -fPIC   -fopenmp -fvisibility=hidden -std=c++11 -std=c++11 -o CMakeFiles/qt.dir/reorder_qt.cc.o -c /home/travis/build/psi4/psi4/psi4/src/psi4/libqt/reorder_qt.cc
/home/travis/build/psi4/psi4/psi4/src/psi4/libqt/reorder_qt.cc:310:1: error: expected ‘}’ at end of input
 }  // namespace psi
 ^
make[5]: *** [src/psi4/libqt/CMakeFiles/qt.dir/reorder_qt.cc.o] Error 1
make[5]: *** Waiting for unfinished jobs....
make[5]: Leaving directory `/home/travis/build/psi4/psi4/build/psi4-core-prefix/src/psi4-core-build'
make[4]: *** [src/psi4/libqt/CMakeFiles/qt.dir/all] Error 2
make[4]: Leaving directory `/home/travis/build/psi4/psi4/build/psi4-core-prefix/src/psi4-core-build'
make[3]: *** [all] Error 2
make[3]: Leaving directory `/home/travis/build/psi4/psi4/build/psi4-core-prefix/src/psi4-core-build'
make[2]: *** [psi4-core-prefix/src/psi4-core-stamp/psi4-core-build] Error 2
make[2]: Leaving directory `/home/travis/build/psi4/psi4/build'
make[1]: *** [CMakeFiles/psi4-core.dir/all] Error 2
make[1]: Leaving directory `/home/travis/build/psi4/psi4/build'
make: *** [all] Error 2
```

**Comment by andysim** [comment]
As much as I'd like to blame c-f, this one's on me.  Must've messed up the conflict resolution.  Thanks for the heads-up
