### PR TITLE
Fix Numpy Python detection in Windows for new NumPy

### LINKED ISSUE #2614: Psi4 v1.6 installation issue Windows, conda, Python 3.8
When following the suggested path for installation on Windows using conda and Python 3.8, even setting up a new environment on version 3.8, I cannot get it to run, as the "psi4 --test" command gives an error.

On WSL using either conda or the installer I also cannot get it to work.
I create a new environment with: 
```
conda create -n psi16 python=3.8
conda activate psi16
conda update --all
conda install psi4 python=3.8 -c psi4 -c conda-forge
psi4 --test
```

This error was encountered on two separate machines running up to date Windows 10 Pro.

Running the test gives me the following error: 
Traceback (most recent call last):
  File "Path\psi4conda\envs\psi16\Scripts\psi4-script.py", line 187, in <module>
    import psi4  # isort:skip
  File "Path\psi4conda\envs\psi16\lib\site-packages\psi4\__init__.py", line 76, in <module>
    from .driver import endorsed_plugins
  File "Path\psi4conda\envs\psi16\lib\site-packages\psi4\driver\__init__.py", line 46, in <module>
    from psi4.driver.molutil import *
  File "Path\psi4conda\envs\psi16\lib\site-packages\psi4\driver\molutil.py", line 36, in <module>
    from psi4.driver.p4util import temp_circular_import_blocker
  File "Path\psi4conda\envs\psi16\lib\site-packages\psi4\driver\p4util\__init__.py", line 32, in <module>
    from .util import *
  File "Path\psi4conda\envs\psi16\lib\site-packages\psi4\driver\p4util\util.py", line 37, in <module>
    from psi4.driver.procrouting import *
  File "Path\psi4conda\envs\psi16\lib\site-packages\psi4\driver\procrouting\__init__.py", line 29, in <module>
    from .proc_table import procedures, hooks, energy_only_methods, integrated_basis_methods
  File "Path\psi4conda\envs\psi16\lib\site-packages\psi4\driver\procrouting\proc_table.py", line 32, in <module>
    from . import sapt
  File "Path\psi4conda\envs\psi16\lib\site-packages\psi4\driver\procrouting\sapt\__init__.py", line 29, in <module>
    from .sapt_proc import run_sapt_dft, sapt_dft, run_sf_sapt
  File "Path\psi4conda\envs\psi16\lib\site-packages\psi4\driver\procrouting\sapt\sapt_proc.py", line 36, in <module>
    from psi4.driver.procrouting.proc import scf_helper
  File "Pathpsi4conda\envs\psi16\lib\site-packages\psi4\driver\procrouting\proc.py", line 55, in <module>
    from . import proc_util
  File "Path\psi4conda\envs\psi16\lib\site-packages\psi4\driver\procrouting\proc_util.py", line 38, in <module>
    from psi4.driver.procrouting.sapt import fisapt_proc
  File "Path\psi4conda\envs\psi16\lib\site-packages\psi4\driver\procrouting\sapt\fisapt_proc.py", line 34, in <module>
    from .. import empirical_dispersion
  File "Path\psi4conda\envs\psi16\lib\site-packages\psi4\driver\procrouting\empirical_dispersion.py", line 38, in <module>
    from psi4.driver import driver_findif
  File "Path\psi4conda\envs\psi16\lib\site-packages\psi4\driver\driver_findif.py", line 153, in <module>
    from psi4.driver.task_base import AtomicComputer, BaseComputer, EnergyGradientHessianWfnReturn
  File "Path\psi4conda\envs\psi16\lib\site-packages\psi4\driver\task_base.py", line 67, in <module>
    class AtomicComputer(BaseComputer):
  File "Path\psi4conda\envs\psi16\lib\site-packages\psi4\driver\task_base.py", line 75, in AtomicComputer
    keywords: Dict[str, Any] = Field(default_factory=dict, description="The keywords to use in the computation.")
TypeError: Field() missing 1 required positional argument: 'default'

### PR DESCRIPTION
**Pull request by loriab**
## Todos
- [x] Something about how CMake detects NumPy during FindPython is different between NumPy 1.22 and 1.23; only on Windows. No apparent changes in CMake FindPython. No apparent changes in conda NumPy recipe. All header files in the same places in a Windows c-f 1.22 and 1.23 NumPy distribution. Linux builds fine with a c-f NumPy 1.23. I don't know what's the real change, so we'll tell CMake where to look in the Azure recipe and pass the hint on to psi4/CM for the second `find_package(Python ...)`.
- [x] My other theory for solving the Azure problem was that my patched `anaconda-client` was behind the times. That wasn't the problem, but it's updated to v1.10.0 anyways.
- [x] Pinned qcelemental and qcengine in Windows recipe
  * There's upcoming changes to those packages such that all of psi4 should be pinned and then advanced with the changes. This does that for the Windows recipe.
  * fixes #2614 where Windows conda package had _no_ qcel pinning, so depending on channel order, sometimes took a really old qcel and pydantic. after this, channel order shouldn't matter.

## Checklist
- [ ] Tests added for any new features
- [ ] [All or relevant fraction of full tests run](http://psicode.org/psi4manual/master/build_planning.html#how-to-run-a-subset-of-tests)

## Status
- [x] Ready for review
- [x] Ready for merge

### CODE REVIEW

**Review by JonathonMisiewicz — APPROVED** [review]
🍺 for build fixes, as always.
